version: '3.8'

volumes:
  postgres_data:

services:
  postgres:
    container_name: postgresdatabase
    image: postgres
    environment:
      POSTGRES_USER: 'developer'
      POSTGRES_PASSWORD: 'developer'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=stefanac288@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=parola
    ports:
      - 5050:80